/**
 * Generated by https://github.com/manyuanrong/openapi-deno-client-generator
 */

export interface LogInput {
  timestamp: number;
  category: string;
  service: string;
  level: string;
  userId: string;
  conversationId: string;
  processId: string;
  event: string;
  msg?: string;
}

export class ApiClient {
  constructor(private baseUrl: string, private fetch = globalThis.fetch) {}

  private async request(
    path: string,
    method: string,
    pathsParams: Record<string, string>,
    queryParams: Record<string, any>,
    body: any
  ): Promise<any> {
    for (const parameter in pathsParams) {
      path = path.replace("{" + parameter + "}", pathsParams[parameter]);
    }
    if (Object.keys(queryParams).length > 0) {
      path += "?" + new URLSearchParams(queryParams).toString();
    }
    const response = await this.fetch(this.baseUrl + path, {
      method,
      headers: { "Content-Type": "application/json" },
      body: method != "GET" ? JSON.stringify(body) : undefined,
    });
    if (response.headers.get("content-type")?.includes("application/json")) {
      return await response.json();
    } else {
      return await response.text();
    }
  }

  /**
   * Version
   */
  async version(): Promise<any> {
    return await this.request("/api/version", "GET", {}, {}, {});
  }

  /**
   * 发送日志
   */
  async create(data: LogInput): Promise<any> {
    return await this.request("/api/log", "POST", {}, {}, data);
  }
}
